### ISSUE TITLE
Error modifying NSG with ICMP rule

### ISSUE THREAD

**Issue by runawayjimothy** [oracle-quickstart/oci-cis-landingzone-quickstart#1]
I have a question regarding security-lists and NSGs with respect to ICMP policies.  I found that I had an interesting condition when trying to specify ingress rules for ICMP using the template.  Below is an example of the error output and the same NSG I had created.  If I understand the condition, it seems to be matching against a check for TCP, when in fact the added rule is for ICMP.  I had to comment the lines below out of my NSG in order for the TF plan to complete successfully.
 
 
 Excerpt from .../config/net_2.3-2.4.tf 
 
 
        {
          description   = "PATH MTU Discovery ingress rule for ${local.anywhere}."
          stateless     = false
          protocol      = "1"
          src           = local.anywhere
          src_type      = "CIDR_BLOCK"
          src_port      = null
          dst_port      = null
          icmp_code     = 4
          icmp_type     = 3
        },
        {
          description   = "VCN Connectivity error ingress rule for ${var.vcn_cidr}."
          stateless     = false
          protocol      = "1"
          src           = var.vcn_cidr
          src_type      = "CIDR_BLOCK"
          src_port      = null
          dst_port      = null
          icmp_code     = null
          icmp_type     = 3
        }
 
Error: Attempt to get attribute from null value
 
  on ../../../modules/network/security/main_nsg.tf line 75, in locals:
  75:       } if i.protocol == "6" && i.src_port == null && i.dst_port != null && (i.src != var.anywhere_cidr || (i.src == var.anywhere_cidr && length(setintersection(range(i.dst_port.min,i.dst_port.max+1),var.ports_not_allowed_from_anywhere_cidr)) == 0))
    |----------------
    | i.dst_port is null
 
This value is null, so it does not have any attributes.
 
Error: Attempt to get attribute from null value
 
  on ../../../modules/network/security/main_nsg.tf line 89, in locals:
  89:       } if i.protocol == "6" && i.src_port != null && i.dst_port != null && (i.src != var.anywhere_cidr || (i.src == var.anywhere_cidr && length(setintersection(range(i.dst_port.min,i.dst_port.max+1),var.ports_not_allowed_from_anywhere_cidr)) == 0))
    |----------------
    | i.dst_port is null
 
This value is null, so it does not have any attributes.

**Comment by andrecorreaneto** [comment]
Hi Jim, we'll be looking at this as soon as possible.

**Comment by runawayjimothy** [comment]
I believe I have found the issue in the code evaluation logic for security lists.  I still don't quite understand the expected inputs for ICMP and NSGs.

Security-List
--------------------

It is expected a dst_port to be specified; however, that is being evaluated ahead of the protocol number, which triggers the condition above when dst_port value is set to "null".   However, if the destination port is set to "any", the condition evaluation will continue.

For example....

        {
          description   = "PATH MTU Discovery ingress rule for ${local.anywhere}."
          stateless     = false
          protocol      = "1"
          src           = local.anywhere
          src_type      = "CIDR_BLOCK"
          src_port      = null
          dst_port      = {
            min = 0
            max = 0
          }
          icmp_code     = 4
          icmp_type     = 3
        },
        {
          description   = "VCN Connectivity error ingress rule for ${var.vcn_cidr}."
          stateless     = false
          protocol      = "1"
          src           = var.vcn_cidr
          src_type      = "CIDR_BLOCK"
          src_port      = null
          dst_port      = {
            min = 0
            max = 0
          }
          icmp_code     = null
          icmp_type     = 3
        }

**Comment by runawayjimothy** [comment]
The latest PR #11  has fixed issues with ICMP in NSGs.  Thank you for addressing.
