### ISSUE TITLE
Multi-region deployment using same service_label causes conflict

### ISSUE THREAD

**Issue by lvbirgelen** [oracle-quickstart/oci-cis-landingzone-quickstart#100]
Hi,

When extending to a new region and using the same service_label, deployment of the VAULT-GLOBAL-POLICY service policy causes a error because it already exists as a global resource:
"Error: 409-PolicyAlreadyExists, Policy 'bnds-vault-policy' already exists"

I suggest this should be made conditional depending on the "extend_landing_zone_to_new_region" variable.

https://github.com/oracle-quickstart/oci-cis-landingzone-quickstart/blob/21b539633cae56fc186d97e183ac97d40e31efe3/config/iam_service_policies.tf#L38

Best regards,
Leon.

**Comment by andrecorreaneto** [comment]
Fixed in release 2.5.8.
