### ISSUE TITLE
Possible typo in a cis_reports.py key name: cloud_guard_endable

### ISSUE THREAD

**Issue by LanceBraswell** [oracle-quickstart/oci-cis-landingzone-quickstart#103]
Minor point. This looks like a typo in the key name on this line:

https://github.com/oracle-quickstart/oci-cis-landingzone-quickstart/blob/main/scripts/cis_reports.py#L3884

Namely:

```
"cloud_guard_endable" :  True  if self.__cloud_guard_config_status == 'ENABLED' else False,
```
Should be ```cloud_guard_enable``` or somesuch?

Does not appear to affect the logic in the script as it is only checking the truthiness of all the key values, not specific key names.

**Comment by Halimer** [comment]
@MigRam @LanceBraswell it is not a typo. [Here](https://github.com/oracle-quickstart/oci-cis-landingzone-quickstart/blob/7affe62795c2a8afc42fde0b55b6b4f2171f8e9e/scripts/cis_reports.py#L2878 ) in the code we call [get_configuration](https://docs.oracle.com/en-us/iaas/tools/python/2.110.1/api/cloud_guard/client/oci.cloud_guard.CloudGuardClient.html#oci.cloud_guard.CloudGuardClient.get_configuration) using the Cloud Guard client.  From that, we get an oci.cloud_guard.models.Configuration object which looks the following: 
```
{
  "reporting_region": "us-ashburn-1",
  "self_manage_resources": false,
  "status": "ENABLED"
}
```
The attributes `STATUS_DISABLED` and `STATUS_ENABLED` are constants and not part of the get_configuration response.  Using the response from `get_configuration`, we assign the internal variable self.__cloud_guard_config_status to the `status` returned in the above object.   

Below is some sample code test:
```
config =oci.config.from_file()
cloud_guard_client = oci.cloud_guard.CloudGuardClient(config)
resp = cloud_guard_client.get_configuration(config['tenancy'])
print(resp.data)
```
