### ISSUE TITLE
CIS2.8 Autonomous access restricted

### ISSUE THREAD

**Issue by manuelgilbarrio** [oracle-quickstart/oci-cis-landingzone-quickstart#105]
Hi. I have checked the python cis_reports, and I have doubt about CIS2.8 test. In my configuration, I have a private ADB, so this test must be marked like OK, because the restriction list used in this Autonomous must to be the Security Lists and Network Security Groups applied. But this is not the case, the test gives me a FAIL.
Please could you tell me what conditions are you looking for into the Autonomous DB CIS2.8 test?
Thanks

**Comment by Halimer** [comment]
@manuelgilbarrio You are correct we are missing a check for when an ADB is in a VCN but not using an NSG.  We will be adding this check in the next release.

Thanks,

Josh

**Comment by Halimer** [comment]
This was updated in release 2.6.1: https://github.com/oracle-quickstart/oci-cis-landingzone-quickstart/pull/115 

Thanks,

Josh
