### ISSUE TITLE
Errors terraform init

### ISSUE THREAD

**Issue by DJester1x** [oracle-quickstart/oci-cis-landingzone-quickstart#114]
Hello, I'm very new to terraform and learning quite a bit.  Apologies for my ignorance ahead of time.  

First question: How do I correct provider mismatch referencing hashicorp in the keys.tf file?
I cannot find any references to hashicorp to possibly change the alias which is what I'm being directed to.  Also, I did run the command mentioned in the release notes of the change and received errors as well.  See attached errors.txt and experiment.txt.

Terraform version
Terraform v1.5.3
on linux_amd64
+ provider registry.terraform.io/hashicorp/null v3.2.1
+ provider registry.terraform.io/oracle/oci v5.4.0

Second question: Is it required to only use terraform 1.2.9?
Perhaps I missed it in the materials.  I've noticed in the provider.tf file it requires a terraform version of >= 1.2.0.  I used the latest 1.5.3 and received a bunch of errors.  Some of the errors indicate the modules required version is < 1.3.0.   See attached errors.txt.

That said I did use 1.2.9 but it mentions experimental feature is active in another module.  See attached warnings.txt.  I did plan it and apply and it worked. 

[errors.txt](https://github.com/oracle-quickstart/oci-cis-landingzone-quickstart/files/12129732/errors.txt)
[experiment.txt](https://github.com/oracle-quickstart/oci-cis-landingzone-quickstart/files/12129730/experiment.txt)
[warnings.txt](https://github.com/oracle-quickstart/oci-cis-landingzone-quickstart/files/12129734/warnings.txt)

**Comment by andrecorreaneto** [comment]
Hello there, please run with Terraform >= 1.2.0 and < 1.3.0. We are setting the upper bound to < 1.3.0 in the next release. The reason is that many customers deploy through OCI Resource Manager, that still does not support 1.3.0. Once Resource Manager supports 1.3.0 (happening soon), we will remove the upper bound.
As for aligning the provider mismatch, please try _terraform init -upgrade_. The warnings are harmless.

**Comment by DJester1x** [comment]
Thanks for the reply!  I'll try the -upgrade.  I will also use the resource manager in another tenancy and try it out.

**Comment by DJester1x** [comment]
Yes, I was successful using terraform 1.2.9 terraform and also successful
using OCI resource manager which looks like it uses a version less than
1.3.  It appears to better in the latter as to keep the state file seperate
and accessible by other admins.  Also very friendly to use.  Thanks
for your help.
