### ISSUE TITLE
Deployment Issue

### ISSUE THREAD

**Issue by liamhelmer** [oracle-quickstart/oci-cis-landingzone-quickstart#117]
I can't seem to deploy this as expected. I created a pre-config module, and a landingzone module for my environments, but I get an error during the apply of the cis-landingzone-sandbox module here. The main.tf looks like this:

#main.tf

module "cis-landingzone-pre-config" {
  source = "git@github.com:oracle-quickstart/oci-cis-landingzone-quickstart.git//pre-config?ref=v2.6.2"
  user_ocid = var.user_ocid
  fingerprint = var.fingerprint
  tenancy_ocid = var.tenancy_ocid
  home_region = var.home_region
  private_key_path = var.private_key_path
  unique_prefix = var.unique_prefix
  enclosing_compartment_names = var.enclosing_compartment_names
  }

module "cis-landingzone-sandbox" {
  source = "git@github.com:oracle-quickstart/oci-cis-landingzone-quickstart.git//config?ref=v2.6.2"
  user_ocid = var.user_ocid
  fingerprint = var.fingerprint
  tenancy_ocid = var.tenancy_ocid
  region = var.home_region
  private_key_path = var.private_key_path
  cis_level = 1
  use_enclosing_compartment = true
  existing_enclosing_compartment_ocid = module.cis-landingzone-pre-config.lz_top_compartments.sandbox.id
  service_label = "sandbox"
  hub_spoke_architecture = true
  dmz_vcn_cidr = "10.1.0.0/16"
  }

output "lz_top_compartments" {
  value = module.cis-landingzone-pre-config.lz_top_compartments
  }
  
  and I have a base terraform.tfvars like so:
  #terraform.tfvars:
    user_ocid = "<REDACTED>"
  fingerprint = "REDACTED"
  tenancy_ocid = "REDACTED"
  home_region = "ca-toronto-1"
  private_key_path = "REDACTED"
  unique_prefix = "mogo"
  enclosing_compartment_names = [ "sandbox", "nonprod", "staging", "prod" ]
  
  I get the following error when I do the terraform apply:

module.cis-landingzone-pre-config.module.lz_provisioning_topcmp_group_policy["staging"].oci_identity_policy.these["mogo-staging-provisioning-policy"]: Refreshing state... [id=ocid1.policy.oc1..aaaaaaaasisi2gzi7ugn3law63a6kfqs7fauz4y62h2e2pfxecao7nx6wncq]
module.cis-landingzone-pre-config.module.lz_provisioning_topcmp_group_policy["sandbox"].oci_identity_policy.these["mogo-sandbox-provisioning-policy"]: Refreshing state... [id=ocid1.policy.oc1..aaaaaaaa66sk6hcxlyavuutbhgql67dyrvglardzkkpoylmnjrmxzxwocfoq]
module.cis-landingzone-pre-config.module.lz_provisioning_topcmp_group_policy["prod"].oci_identity_policy.these["mogo-prod-provisioning-policy"]: Refreshing state... [id=ocid1.policy.oc1..aaaaaaaa7evpqve3h7gmlpsxjx6ta2yqv4xkgpzu3dajq5yyafbx6t5nvppq]
module.cis-landingzone-pre-config.module.lz_provisioning_topcmp_group_policy["nonprod"].oci_identity_policy.these["mogo-nonprod-provisioning-policy"]: Refreshing state... [id=ocid1.policy.oc1..aaaaaaaar4f554wqpocdilvnuvugae3jraua5zdighaj7gxpihfgbpp53ema]
╷
│ Warning: Experimental feature "module_variable_optional_attrs" is active
│ 
│   on .terraform/modules/cis-landingzone-sandbox.lz_compartments/compartments/providers.tf line 11, in terraform:
│   11:   experiments = [module_variable_optional_attrs]
│ 
│ Experimental features are subject to breaking changes in future minor or patch releases, based on feedback.
│ 
│ If you have feedback on the design of this feature, please open a GitHub issue to discuss it.
│ 
│ (and 7 more similar warnings elsewhere)
╵
╷
│ Error: Invalid index
│ 
│   on .terraform/modules/cis-landingzone-sandbox/config/mon_notifications.tf line 61, in locals:
│   61:       topic_id            = local.security_topic.id != null ? local.security_topic.id : module.lz_home_region_topics.topics[local.security_topic.key].id
│     ├────────────────
│     │ local.security_topic.key is "SECURITY-TOPIC"
│     │ module.lz_home_region_topics.topics is object with no attributes
│ 
│ The given key does not identify an element in this collection value.
╵
╷
│ Error: Invalid index
│ 
│   on .terraform/modules/cis-landingzone-sandbox/config/mon_notifications.tf line 136, in locals:
│  136:       topic_id            = local.network_topic.id == null ? module.lz_topics.topics[local.network_topic.key].id : local.network_topic.id
│     ├────────────────
│     │ local.network_topic.key is "NETWORK-TOPIC"
│     │ module.lz_topics.topics is object with no attributes
│ 
│ The given key does not identify an element in this collection value.
╵
  ---------
  
  I'm guessing this is a bug in the module somewhere? It looked like 2.6.2 was the right version to use, no?

**Comment by andrecorreaneto** [comment]
Hello liamhelmer,

the config requires the following variables assigned, as they are required by the CIS benchmark:

network_admin_email_endpoints  = ["email-address-1@example.com"]
security_admin_email_endpoints = ["email-address-2@example.com"]

We enforce that in the Resource Manager UI, but you made me realize we are not enforcing them with Terraform CLI.

Please let me know if that solves the problem.

Andre.

**Comment by liamhelmer** [comment]
Awesome, thanks!
I assume the same goes for all the xxxxx_admin_email_endpoints?

**Comment by Halimer** [comment]
Hi liamhelmer,

All the other email admins are not required. The [VARIABLES.md](https://github.com/oracle-quickstart/oci-cis-landingzone-quickstart/blob/main/VARIABLES.md) documents which variables are required and which are optional. In addition it provides documentation on the variable.

**Comment by liamhelmer** [comment]
Awesome, thanks!
Yup, that fixed it. You rock!
module.cis-landingzone-sandbox.module.lz_flow_logs.oci_logging_log.these["sandbox2-dmz-vcn-outdoor-subnet"]: Creation complete after 8s [id=ocid1.log.oc1.ca-toronto-1.amaaaaaau3qpujqaby2u465kueimac3hkpelrvanjahzan322o75qz3z6hba]
module.cis-landingzone-sandbox.module.lz_flow_logs.oci_logging_log.these["sandbox2-0-db-subnet"]: Creation complete after 8s [id=ocid1.log.oc1.ca-toronto-1.amaaaaaau3qpujqax6nxfdus4my2mouyf7e4srwrumwmaltjsjwpmquzvcwq]
module.cis-landingzone-sandbox.module.lz_flow_logs.oci_logging_log.these["sandbox2-0-web-subnet"]: Creation complete after 8s [id=ocid1.log.oc1.ca-toronto-1.amaaaaaau3qpujqay2gadakjm2vnlfovrtzgqfk5qc34ji4qypgio4a222sa]
module.cis-landingzone-sandbox.module.lz_flow_logs.oci_logging_log.these["sandbox2-dmz-vcn-indoor-subnet"]: Creation complete after 8s [id=ocid1.log.oc1.ca-toronto-1.amaaaaaau3qpujqanks27l3g6elr4gjljakoeinhn3kjkln5qgzqta7oqhia]
module.cis-landingzone-sandbox.module.lz_flow_logs.oci_logging_log.these["sandbox2-0-app-subnet"]: Creation complete after 9s [id=ocid1.log.oc1.ca-toronto-1.amaaaaaau3qpujqanjfsmbtcw5in4zyr5rhy7dwxglskg7y7bvxoia5uahqq]
Releasing state lock. This may take a few moments...

Apply complete! Resources: 118 added, 2 changed, 87 destroyed.

Outputs:

**Comment by andrecorreaneto** [comment]
Hi liamhelmer,

just letting you know that the code now checks whether network_admin_email_endpoints and 
security_admin_email_endpoints are provided when running with terraform cli.

Cheers.
