### ISSUE TITLE
Typo in schema.yaml 

### ISSUE THREAD

**Issue by agregory999** [oracle-quickstart/oci-cis-landingzone-quickstart#119]
https://github.com/oracle-quickstart/oci-cis-landingzone-quickstart/blob/d6739c011f32893bcfeec043dea2921632fe7d0b/config/schema.yml#L916

**Comment by andrecorreaneto** [comment]
Ack. We'll get it changed in the next release. Thanks.

**Comment by andrecorreaneto** [comment]
Fixed
