### ISSUE TITLE
Define schema.yaml

### ISSUE THREAD

**Issue by agregory999** [oracle-quickstart/oci-cis-landingzone-quickstart#12]
For Oracle Resource Manager, if we use conditional booleans, dropdown values (region key for example), and then sections for the config, it will be closer to self documenting.  We can provide a title, description, and regex expression for validity for each terraform variable that is required.  The oci-cloudnative repo has this kind of validation in its terraform for ORM.

**Comment by andrecorreaneto** [comment]
Thanks a lot Andrew. We'll include schema.yaml in the next release of Landing Zone.

**Comment by Halimer** [comment]
Added in commit: https://github.com/oracle-quickstart/oci-cis-landingzone-quickstart/commit/ccc028ab8cdec4b17475d1643fadc9b0fb8fa77c#diff-0309db2a89c48166b1a5559bd173631fef40b9684dc18c7cc617372b9aee86b1
