### ISSUE TITLE
Hidden Variables

### ISSUE THREAD

**Issue by integration01** [oracle-quickstart/oci-cis-landingzone-quickstart#122]
Should be tenancy_ocid, user_ocid,region - currently they come up as optional but required in the Stack edit page.

https://github.com/oracle-quickstart/oci-cis-landingzone-quickstart/blob/26aa216627a45ab3226d8766a4563aec5b40d9ef/workloads/generic_workload_compartments/schema.yml#L88

**Comment by andrecorreaneto** [comment]
Ack. Being evaluated.
