### ISSUE TITLE
Issue in Services Policy creation with pre-config pattern

### ISSUE THREAD

**Issue by liamhelmer** [oracle-quickstart/oci-cis-landingzone-quickstart#124]
Your services policy creation is broken if using the pre-config/config pattern with reduced privileges. This line here:
https://github.com/oracle-quickstart/oci-cis-landingzone-quickstart/blob/main/modules/iam/iam-services-policy/main.tf#L31C13-L31C13
has the the services policies being created at the top level of the tenancy, instead of a the landingzone root.

**Comment by liamhelmer** [comment]
I notice that there's a variable there called "enable_tenancy_level_policies" that defaults to "true", however, there's no way to set it.

**Comment by liamhelmer** [comment]
Solving it by adding the following alongside the preconfig, and manually setting the default of that variable to false. Wish me luck:
------------
locals {
  cloud_guard_statements = [
    "Allow service cloudguard to read all-resources in tenancy",
    "Allow service cloudguard to use network-security-groups in tenancy"]

  vss_statements = [
    "Allow service vulnerability-scanning-service to manage instances in tenancy",
    "Allow service vulnerability-scanning-service to read compartments in tenancy",
    "Allow service vulnerability-scanning-service to read repos in tenancy",
    "Allow service vulnerability-scanning-service to read vnics in tenancy",
    "Allow service vulnerability-scanning-service to read vnic-attachments in tenancy"
  ]

  k8s_statements = [ "ALLOW any-user to manage volumes in TENANCY where request.principal.type = 'cluster'",
      "ALLOW any-user to manage volume-attachments in TENANCY where request.principal.type = 'cluster'" ]

  os_mgmt_statements = [
    "Allow service osms to read instances in tenancy"
  ]

}

resource "oci_identity_policy" "services-policy" {
    compartment_id = var.tenancy_ocid
    name           = "global-services-policy"
    description    = "Landing Zone policy for OCI services."
    statements     = concat(local.cloud_guard_statements, local.vss_statements, local.os_mgmt_statements, local.k8s_statements)
    freeform_tags = {"cost-center" = "internal"}
}

**Comment by liamhelmer** [comment]
This didn't fix it, because the code I linked to isn't used my this repo. Instead, it actually uses this code, which contains no such option:
https://github.com/oracle-quickstart/terraform-oci-cis-landing-zone-iam/blob/main/policies/services_policy.tf

**Comment by liamhelmer** [comment]
Yeah, I don't see any way to fix this without basically rewriting this whole section of the module. Going to just give it more permissions. But this kind of bug completely defeats the purpose of privilege segregation: there's simply no way to deploy this as currently written without permissions to write policies on the root of the tenancy. And that effectively gives you privileges to do everything else.

**Comment by liamhelmer** [comment]
For reference, here's what the error is when it breaks:
module.cis-landingzone-nonprod.module.cis-landingzone.module.lz_topics.oci_ons_notification_topic.these["BUDGET-TOPIC"]: Creating...
module.cis-landingzone-nonprod.module.cis-landingzone.module.lz_services_policy.oci_identity_policy.these["nonprod-services-policy"]: Creating...
╷
│ Error: 404-NotAuthorizedOrNotFound, Authorization failed or requested resource not found
│ Suggestion: Either the resource has been deleted or service Identity Policy need policy to access this resource. Policy reference: https://docs.oracle.com/en-us/iaas/Content/Identity/Reference/policyreference.htm
│ Documentation: https://registry.terraform.io/providers/oracle/oci/latest/docs/resources/identity_policy 
│ API Reference: https://docs.oracle.com/iaas/api/#/en/identity/20160918/Policy/CreatePolicy 
│ Request Target: POST https://identity.ca-toronto-1.oci.oraclecloud.com/20160918/policies 
│ Provider version: 5.19.0, released on 2023-11-01.  
│ Service: Identity Policy 
│ Operation Name: CreatePolicy 
│ OPC request ID: f1b81f16b344e6fd666db287e1ce08c1/AA1B8A5D72F04C4DDF75CAB4F9DE5947/16372074CBBAE97794DBA615D316E0BA 
│ 
│ 
│   with module.cis-landingzone-nonprod.module.cis-landingzone.module.lz_services_policy.oci_identity_policy.these["nonprod-services-policy"],
│   on .terraform/modules/cis-landingzone-nonprod.cis-landingzone.lz_services_policy/policies/main.tf line 22, in resource "oci_identity_policy" "these":
│   22: resource "oci_identity_policy" "these" {
│ 
╵
╷
│ Error: 404-NotAuthorizedOrNotFound, Authorization failed or requested resource not found.
│ Suggestion: Either the resource has been deleted or service Ons Notification Topic need policy to access this resource. Policy reference: https://docs.oracle.com/en-us/iaas/Content/Identity/Reference/policyreference.htm
│ Documentation: https://registry.terraform.io/providers/oracle/oci/latest/docs/resources/ons_notification_topic 
│ API Reference: https://docs.oracle.com/iaas/api/#/en/notification/20181201/NotificationTopic/CreateTopic 
│ Request Target: POST https://notification.ca-toronto-1.oraclecloud.com/20181201/topics 
│ Provider version: 5.19.0, released on 2023-11-01.  
│ Service: Ons Notification Topic 
│ Operation Name: CreateTopic 
│ OPC request ID: c6b7dca6c679b8f841c19f4f171b9b25/8DFDA38B21FC8FB49657F01B30EAFFDB/959A990638C7AF00D5B04E117267AA19 
│ 
│ 
│   with module.cis-landingzone-nonprod.module.cis-landingzone.module.lz_topics.oci_ons_notification_topic.these["BUDGET-TOPIC"],
│   on .terraform/modules/cis-landingzone-nonprod.cis-landingzone/modules/monitoring/topics-v2/topics/main.tf line 12, in resource "oci_ons_notification_topic" "these":
│   12: resource "oci_ons_notification_topic" "these" {
│

**Comment by andrecorreaneto** [comment]
Hello liamhelmer,

we realize there's indeed a regression in [https://github.com/oracle-quickstart/oci-cis-landingzone-quickstart/blob/main/config/iam_service_policies.tf](https://github.com/oracle-quickstart/oci-cis-landingzone-quickstart/blob/main/config/iam_service_policies.tf) that affects the preconfig/config scenario.

If you have the code locally, please replace line 17, that currently reads:

policies_configuration = var.extend_landing_zone_to_new_region == false && var.enable_template_policies == false ? local.services_policies_configuration : local.empty_services_policies_configuration

 with this:

policies_configuration = var.extend_landing_zone_to_new_region == false && var.enable_template_policies == false ? (local.use_existing_root_cmp_grants == true ? local.empty_services_policies_configuration : local.services_policies_configuration) : local.empty_services_policies_configuration

Then, when deploying config, make sure to set variable **policies_in_root_compartment** to **"USE"**, as documented in:
 
- https://www.ateam-oracle.com/post/deployment-modes-for-cis-oci-landing-zone
- https://github.com/oracle-quickstart/oci-cis-landingzone-quickstart/blob/main/VARIABLES.md

We'll get it fixed in main line with highest priority.

Thanks for reaching out and reporting.

Andre.

**Comment by andrecorreaneto** [comment]
Hey there, I did read all messages. Service policies and all policies (by the way) are created by the remote module, as you noted. The fix I am suggesting you to execute prevents services policies from being created at the root compartment by the remote module, as the executing user does not have permissions to do so. If pre-config has been executed, the services policies are already created in the root compartment.

**Comment by andrecorreaneto** [comment]
This has been fixed and working according to design.
