### ISSUE TITLE
Lack of Version Control of external modules

### ISSUE THREAD

**Issue by liamhelmer** [oracle-quickstart/oci-cis-landingzone-quickstart#126]
Please make sure that future versions of this have version control on external modules. I notice that you're using external (oracle maintained) modules without specifying the specific version to use in a number of places. Best practice is to avoid this:

https://developer.hashicorp.com/terraform/language/expressions/version-constraints#best-practices

This list is possibly not exhaustive, but it's a good start:
../oci-cis-landingzone-quickstart/config/iam_dynamic_groups.tf:20:  source = "github.com/oracle-quickstart/terraform-oci-cis-landing-zone-iam/dynamic-groups"
../oci-cis-landingzone-quickstart/config/iam_groups.tf:27:  source = "github.com/oracle-quickstart/terraform-oci-cis-landing-zone-iam/groups"
../oci-cis-landingzone-quickstart/config/iam_policies.tf:587:  source = "github.com/oracle-quickstart/terraform-oci-cis-landing-zone-iam/policies"
../oci-cis-landingzone-quickstart/config/iam_policies.tf:595:  source = "github.com/oracle-quickstart/terraform-oci-cis-landing-zone-iam/policies"
../oci-cis-landingzone-quickstart/config/iam_service_policies.tf:14:  source = "github.com/oracle-quickstart/terraform-oci-cis-landing-zone-iam/policies"
../oci-cis-landingzone-quickstart/config/iam_template_policies.tf:21:  source = "github.com/oracle-quickstart/terraform-oci-cis-landing-zone-iam/policies"

**Comment by andrecorreaneto** [comment]
Well observed. This is going to be available in next refresh, v2.7.0.

**Comment by andrecorreaneto** [comment]
Available in v2.7.0.
