### ISSUE TITLE
Feature Request: add flag to turn off subnetting.

### ISSUE THREAD

**Issue by liamhelmer** [oracle-quickstart/oci-cis-landingzone-quickstart#127]
It's not possible with this terraform to have no subnets defined.

2 basic issues are encountered when trying to have no subnets deployed by this:

1) specifying no var subnets_names variable results in a default set of subnets being deployed: web, app, db. I would like to be able to have a parameter that simply turns off subnet provisioning if I don't want any deployed.

2) even if if I alter the terraform to have no subnets specified, it's not possible to deploy, as too many other modules (rules, routes, etc) depend on the subnets being deployed, particularly in the code around bastion ACLs and a few other places

**Comment by Halimer** [comment]
Appreciate your feedback would you help us understand this requirement more. Your goal to create a VCN with no subnets in it, correct?  If so what is the use case this supports? 

As a work around you could deploy a Landing Zone with no VCN and then use our new CIS networking module to deploy a netowrk.  The modules is available here: [https://github.com/oracle-quickstart/terraform-oci-cis-landing-zone-networking](https://github.com/oracle-quickstart/terraform-oci-cis-landing-zone-networking)
