### ISSUE TITLE
some problem with run terraform for creation of LZ in oci

### ISSUE THREAD

**Issue by EBO2022E** [oracle-quickstart/oci-cis-landingzone-quickstart#131]
Hello,
Configure perfectly the file 
quickstart-input.tfvars
with all parametters 
and when i run: 
terraform plan in the same path i receive these error:
- lz_vcn_spokes in ../modules/network/vcn-basic
╷
│ Error: Provider type mismatch
│ 
│   on keys.tf line 44, in module "lz_keys":
│   44:     oci.home = oci.home
│ 
│ The local name "oci.home" in the root module represents provider "hashicorp/oci", but
│ "oci.home" in module.lz_keys represents "oracle/oci".
│ 
│ Each provider has its own distinct configuration schema and provider types, so this module's
│ "oci.home" can be assigned only a configuration for oracle/oci, which is not required by
│ module.lz_keys.
╵

╷
│ Error: Provider type mismatch
│ 
│   on keys.tf line 64, in module "lz_service_connector_keys":
│   64:     oci.home = oci.home
│ 
│ The local name "oci.home" in the root module represents provider "hashicorp/oci", but
│ "oci.home" in module.lz_service_connector_keys represents "oracle/oci".
│ 
│ Each provider has its own distinct configuration schema and provider types, so this module's
│ "oci.home" can be assigned only a configuration for oracle/oci, which is not required by
│ module.lz_service_connector_keys.
╵

╷
│ Error: Provider type mismatch
│ 
│   on mon_service_connector.tf line 45, in module "lz_service_connector":
│   45:     oci.home = oci.home
│ 
│ The local name "oci.home" in the root module represents provider "hashicorp/oci", but
│ "oci.home" in module.lz_service_connector represents "oracle/oci".
│ 
│ Each provider has its own distinct configuration schema and provider types, so this module's
│ "oci.home" can be assigned only a configuration for oracle/oci, which is not required by
│ module.lz_service_connector.
╵

╷
│ Error: Unsupported Terraform Core version
│ 
│   on provider.tf line 24, in terraform:
│   24:   required_version = ">= 1.2.0, < 1.3.0"
│ 
│ This configuration does not support Terraform version 1.5.0. To proceed, either choose
│ another supported Terraform version or update this version constraint. Version constraints
│ are normally set for good reason, so updating the constraint may lead to other errors or
│ unexpected behavior.
╵

╷
│ Error: Unsupported Terraform Core version
│ 
│   on .terraform/modules/lz_compartments/compartments/providers.tf line 5, in terraform:
│    5:   required_version = "< 1.3.0"
│ 
│ Module module.lz_compartments (from
│ git::https://github.com/oracle-quickstart/terraform-oci-cis-landing-zone-iam.git//compartments?ref=v0.1.6)
│ does not support Terraform version 1.5.0. To proceed, either choose another supported
│ Terraform version or update this version constraint. Version constraints are normally set for
│ good reason, so updating the constraint may lead to other errors or unexpected behavior.
╵

╷
│ Error: Unsupported Terraform Core version
│ 
│   on .terraform/modules/lz_dynamic_groups/dynamic-groups/providers.tf line 5, in terraform:
│    5:   required_version = "< 1.3.0"
│ 
│ Module module.lz_dynamic_groups (from
│ git::https://github.com/oracle-quickstart/terraform-oci-cis-landing-zone-iam.git//dynamic-groups)
│ does not support Terraform version 1.5.0. To proceed, either choose another supported
│ Terraform version or update this version constraint. Version constraints are normally set for
│ good reason, so updating the constraint may lead to other errors or unexpected behavior.
╵

╷
│ Error: Unsupported Terraform Core version
│ 
│   on .terraform/modules/lz_groups/groups/providers.tf line 5, in terraform:
│    5:   required_version = "< 1.3.0"
│ 
│ Module module.lz_groups (from
│ git::https://github.com/oracle-quickstart/terraform-oci-cis-landing-zone-iam.git//groups)
│ does not support Terraform version 1.5.0. To proceed, either choose another supported
│ Terraform version or update this version constraint. Version constraints are normally set for
│ good reason, so updating the constraint may lead to other errors or unexpected behavior.
╵

╷
│ Error: Unsupported Terraform Core version
│ 
│   on .terraform/modules/lz_policies/policies/providers.tf line 5, in terraform:
│    5:   required_version = "< 1.3.0"
│ 
│ Module module.lz_policies (from
│ git::https://github.com/oracle-quickstart/terraform-oci-cis-landing-zone-iam.git//policies)
│ does not support Terraform version 1.5.0. To proceed, either choose another supported
│ Terraform version or update this version constraint. Version constraints are normally set for
│ good reason, so updating the constraint may lead to other errors or unexpected behavior.
╵

╷
│ Error: Unsupported Terraform Core version
│ 
│   on .terraform/modules/lz_root_policies/policies/providers.tf line 5, in terraform:
│    5:   required_version = "< 1.3.0"
│ 
│ Module module.lz_root_policies (from
│ git::https://github.com/oracle-quickstart/terraform-oci-cis-landing-zone-iam.git//policies)
│ does not support Terraform version 1.5.0. To proceed, either choose another supported
│ Terraform version or update this version constraint. Version constraints are normally set for
│ good reason, so updating the constraint may lead to other errors or unexpected behavior.
╵

╷
│ Error: Unsupported Terraform Core version
│ 
│   on .terraform/modules/lz_services_policy/policies/providers.tf line 5, in terraform:
│    5:   required_version = "< 1.3.0"
│ 
│ Module module.lz_services_policy (from
│ git::https://github.com/oracle-quickstart/terraform-oci-cis-landing-zone-iam.git//policies)
│ does not support Terraform version 1.5.0. To proceed, either choose another supported
│ Terraform version or update this version constraint. Version constraints are normally set for
│ good reason, so updating the constraint may lead to other errors or unexpected behavior.
╵

╷
│ Error: Unsupported Terraform Core version
│ 
│   on .terraform/modules/lz_template_policies/policies/providers.tf line 5, in terraform:
│    5:   required_version = "< 1.3.0"
│ 
│ Module module.lz_template_policies (from
│ git::https://github.com/oracle-quickstart/terraform-oci-cis-landing-zone-iam.git//policies)
│ does not support Terraform version 1.5.0. To proceed, either choose another supported
│ Terraform version or update this version constraint. Version constraints are normally set for
│ good reason, so updating the constraint may lead to other errors or unexpected behavior.
╵

╷
│ Error: Unsupported Terraform Core version
│ 
│   on .terraform/modules/lz_top_compartment/compartments/providers.tf line 5, in terraform:
│    5:   required_version = "< 1.3.0"
│ 
│ Module module.lz_top_compartment (from
│ git::https://github.com/oracle-quickstart/terraform-oci-cis-landing-zone-iam.git//compartments?ref=v0.1.6)
│ does not support Terraform version 1.5.0. To proceed, either choose another supported
│ Terraform version or update this version constraint. Version constraints are normally set for
│ good reason, so updating the constraint may lead to other errors or unexpected behavior.
╵

➜  config-live-demo git:(main) ✗ 

how can i fix them please?
Thanks a lot.

**Comment by EBO2022E** [comment]
i fix the right path where i have modules/security/keys and fix some error in the file keys.tf
Now I have the following errors:
╷
│ Error: Unsupported Terraform Core version
│ 
│   on provider.tf line 24, in terraform:
│   24:   required_version = ">= 1.2.0, < 1.3.0"
│ 
│ This configuration does not support Terraform version 1.5.0. To proceed, either choose
│ another supported Terraform version or update this version constraint. Version constraints
│ are normally set for good reason, so updating the constraint may lead to other errors or
│ unexpected behavior.
╵

╷
│ Error: Unsupported Terraform Core version
│ 
│   on .terraform/modules/lz_compartments/compartments/providers.tf line 5, in terraform:
│    5:   required_version = "< 1.3.0"
│ 
│ Module module.lz_compartments (from
│ git::https://github.com/oracle-quickstart/terraform-oci-cis-landing-zone-iam.git//compartments?ref=v0.1.6)
│ does not support Terraform version 1.5.0. To proceed, either choose another supported
│ Terraform version or update this version constraint. Version constraints are normally set for
│ good reason, so updating the constraint may lead to other errors or unexpected behavior.
╵

╷
│ Error: Unsupported Terraform Core version
│ 
│   on .terraform/modules/lz_dynamic_groups/dynamic-groups/providers.tf line 5, in terraform:
│    5:   required_version = "< 1.3.0"
│ 
│ Module module.lz_dynamic_groups (from
│ git::https://github.com/oracle-quickstart/terraform-oci-cis-landing-zone-iam.git//dynamic-groups)
│ does not support Terraform version 1.5.0. To proceed, either choose another supported
│ Terraform version or update this version constraint. Version constraints are normally set for
│ good reason, so updating the constraint may lead to other errors or unexpected behavior.
╵

╷
│ Error: Unsupported Terraform Core version
│ 
│   on .terraform/modules/lz_groups/groups/providers.tf line 5, in terraform:
│    5:   required_version = "< 1.3.0"
│ 
│ Module module.lz_groups (from
│ git::https://github.com/oracle-quickstart/terraform-oci-cis-landing-zone-iam.git//groups)
│ does not support Terraform version 1.5.0. To proceed, either choose another supported
│ Terraform version or update this version constraint. Version constraints are normally set for
│ good reason, so updating the constraint may lead to other errors or unexpected behavior.
╵

╷
│ Error: Unsupported Terraform Core version
│ 
│   on .terraform/modules/lz_policies/policies/providers.tf line 5, in terraform:
│    5:   required_version = "< 1.3.0"
│ 
│ Module module.lz_policies (from
│ git::https://github.com/oracle-quickstart/terraform-oci-cis-landing-zone-iam.git//policies)
│ does not support Terraform version 1.5.0. To proceed, either choose another supported
│ Terraform version or update this version constraint. Version constraints are normally set for
│ good reason, so updating the constraint may lead to other errors or unexpected behavior.
╵

╷
│ Error: Unsupported Terraform Core version
│ 
│   on .terraform/modules/lz_root_policies/policies/providers.tf line 5, in terraform:
│    5:   required_version = "< 1.3.0"
│ 
│ Module module.lz_root_policies (from
│ git::https://github.com/oracle-quickstart/terraform-oci-cis-landing-zone-iam.git//policies)
│ does not support Terraform version 1.5.0. To proceed, either choose another supported
│ Terraform version or update this version constraint. Version constraints are normally set for
│ good reason, so updating the constraint may lead to other errors or unexpected behavior.
╵

╷
│ Error: Unsupported Terraform Core version
│ 
│   on .terraform/modules/lz_services_policy/policies/providers.tf line 5, in terraform:
│    5:   required_version = "< 1.3.0"
│ 
│ Module module.lz_services_policy (from
│ git::https://github.com/oracle-quickstart/terraform-oci-cis-landing-zone-iam.git//policies)
│ does not support Terraform version 1.5.0. To proceed, either choose another supported
│ Terraform version or update this version constraint. Version constraints are normally set for
│ good reason, so updating the constraint may lead to other errors or unexpected behavior.
╵

╷
│ Error: Unsupported Terraform Core version
│ 
│   on .terraform/modules/lz_template_policies/policies/providers.tf line 5, in terraform:
│    5:   required_version = "< 1.3.0"
│ 
│ Module module.lz_template_policies (from
│ git::https://github.com/oracle-quickstart/terraform-oci-cis-landing-zone-iam.git//policies)
│ does not support Terraform version 1.5.0. To proceed, either choose another supported
│ Terraform version or update this version constraint. Version constraints are normally set for
│ good reason, so updating the constraint may lead to other errors or unexpected behavior.
╵

╷
│ Error: Unsupported Terraform Core version
│ 
│   on .terraform/modules/lz_top_compartment/compartments/providers.tf line 5, in terraform:
│    5:   required_version = "< 1.3.0"
│ 
│ Module module.lz_top_compartment (from
│ git::https://github.com/oracle-quickstart/terraform-oci-cis-landing-zone-iam.git//compartments?ref=v0.1.6)
│ does not support Terraform version 1.5.0. To proceed, either choose another supported
│ Terraform version or update this version constraint. Version constraints are normally set for
│ good reason, so updating the constraint may lead to other errors or unexpected behavior.
╵

**Comment by andrecorreaneto** [comment]
It seems your terraform version is unsupported by CIS LZ.
CIS LZ requires terraform < 1.3.0.

So download terraform 1.2.9 and use it to run CIS LZ.

```
│ Error: Unsupported Terraform Core version
│
│ on .terraform/modules/lz_top_compartment/compartments/providers.tf line 5, in terraform:
│ 5: required_version = "< 1.3.0"
```

**Comment by andrecorreaneto** [comment]
Can you elaborate what you've changed in keys.tf? There should be nothing to change in the code.
The provider mismatch is typically solved with ```terraform init -upgrade```
