### ISSUE TITLE
OCI Config not found issue

### ISSUE THREAD

**Issue by Harish2892** [oracle-quickstart/oci-cis-landingzone-quickstart#14]
I am using Windows Subsystem for Linux . I got the "** OCI Config was not found here : ~/.oci/config or env varibles missing, aborting **" error.
My cis_reports.py, config file, oci public key, private key & fingerprint is located in echo$Home.
Plz help

**Comment by Halimer** [comment]
The script by default uses the `DEFAULT` profile from the `~/.oci/config` file. The easiest thing to do is create a `.oci` directory in your home directory then copy your `config` file there.  Make sure your `config` file looks like the below and the path to the API Key is correct. 

```
[DEFAULT]
tenancy=<tenancy_ocid>
region=us-ashburn-1
user=<user_ocid>
fingerprint=<api_key_finger_print>
key_file=/path_to_my_private_key_file.pem
```

**Comment by Harish2892** [comment]
Hi  Josh ,
I have created .oci directory in home directory & copied all the files
there.
Still I got the same error message.
Please refer to the screenshot below.

**Comment by Halimer** [comment]
Would you try to install  the oci cli in your WSL to test your `~/.oci` configuration.  [Here](https://docs.oracle.com/en-us/iaas/Content/API/SDKDocs/cliinstall.htm) are the directions I used the Linux directions for my WSL environment. I have successfully run the script from my WSL environment please see the output below:
```
(python-venv) hammer@DESKTOP-BKHQ31S:~$ pwd
/home/hammer
(python-venv) hammer@DESKTOP-BKHQ31S:~$ ls
2021-04-27  cis_reports.py  python-venv
(python-venv) hammer@DESKTOP-BKHQ31S:~$ ls ~/.oci/
config  oci_api_key.pem
(python-venv) hammer@DESKTOP-BKHQ31S:~$ python3 cis_reports.py

##########################################################################################
#                                 Running CIS Reports...                                 #
##########################################################################################
Written by Josh Hammer & Andre Correa, updated April 22, 2021.
Starts at 2021-04-29 17:39:03

##########################################################################################
#                  Processing Tenancy Data for orasenatdpltsecitom01...                  #
##########################################################################################
Processing Compartments...
Processing Cloud Guard Configuration...
Processing Vaults and Keys...
Processing Audit Configuration...
Processing Tenancy Password Policy...
Processing IAM Policies in root...
```

**Comment by anassb** [comment]
if you are using a passphrase with your private key then the issue may happen. if this is the case add the pass_phrase parameter. 

tenancy=XXXXXXXXXX
region=XX
user=XXXXXXXXXXXXXXX
fingerprint=XXXXXXXXXX
key_file=/home/oracle/.oci/oci_api_key.pem
pass_phrase=Passphrase

**Comment by goingDataway** [comment]
@Harish2892 I am also getting the same error, let me know the solution if resolved.
