### ISSUE TITLE
Compliance Scripts Output files have spaces and dots in names

### ISSUE THREAD

**Issue by agregory999** [oracle-quickstart/oci-cis-landingzone-quickstart#15]
We may want to consider making it such that the names of the output files do not have spaces and dots in them, as it makes them more difficult to deal with.  If the names all follow the pattern with `cis_<type>_<subtype>.csv`, we wind up with filenames like this:
```
cis_Asset Management_5.2.csv
cis_Identity and Access Management_1.1.csv
cis_Identity and Access Management_1.3.csv
cis_Identity and Access Management_1.7.csv
cis_Logging and Monitoring_3.17.csv
cis_Object Storage_4.2.csv
cis_summary_report.csv
```
Although this can be overcome, it could cause issues for downstream scripts and processes that may read this files.  
```
(python-venv) andrew_gre@cloudshell:scripts (us-ashburn-1)$ cat 2021-05-03/cis_Logging and Monitoring_3.17.csv
cat: 2021-05-03/cis_Logging: No such file or directory
cat: and: No such file or directory
cat: Monitoring_3.17.csv: No such file or directory
```

**Comment by Halimer** [comment]
Fixed in commit: https://github.com/oracle-quickstart/oci-cis-landingzone-quickstart/commit/2a3ed1fb8daaacf813de1f9bf67e264773b418ab
