### ISSUE TITLE
module network outputs.tf should return full objects (TF)

### ISSUE THREAD

**Issue by trvsmtchll** [oracle-quickstart/oci-cis-landingzone-quickstart#2]
The outputs of the network module should return objects so they can easily be used in further TF automation.
Please add these to ./modules/network/outputs.tf 

output "vcn" {
  description = "VCN object"
  value       = oci_core_vcn.this
}

output "subnet_objects" {
  description = "The managed subnet objects."
  value = oci_core_subnet.these
}

output "rt_objects" {
  description = "The managed route table objects."
  value = oci_core_route_table.these
}

Thanks,
Travis

**Comment by Halimer** [comment]
Updated in merge 5. Some outputs are mapped by object name.
