### ISSUE TITLE
Notification Not Working by Adding User into Group

### ISSUE THREAD

**Issue by dennisqdx** [oracle-quickstart/oci-cis-landingzone-quickstart#31]
Hello,
I failed to receive the notification by testing adding a user into the appdev group.  Could you please confirm it?

**Comment by andrecorreaneto** [comment]
Hi Dennis, when Landing Zone sets up notifications, OCI sends you an email to confirm notification subscription. Make sure to confirm the subscription. After that, you should be able to receive notifications about users being added to groups.
