### ISSUE TITLE
Wrong metric_compartment_id

### ISSUE THREAD

**Issue by lvbirgelen** [oracle-quickstart/oci-cis-landingzone-quickstart#41]
https://github.com/oracle-quickstart/oci-cis-landingzone-quickstart/blob/a0c3f3a9f87e1930cb027813ff6759cf977f1312/config/mon_alarms.tf#L142

This should be:
metric_compartment_id = local.network_topic.cmp_id

**Comment by andrecorreaneto** [comment]
Thanks for catching that. Fixed.
