### ISSUE TITLE
Typo in the description

### ISSUE THREAD

**Issue by andytael** [oracle-quickstart/oci-cis-landingzone-quickstart#44]
When deploying using ORM there is a typo in the description field:

A stack to deploy a set of CIS (Center for Internet Security) compliant resources in an OCI tenancy. The Secure Landing Zone is the combination of CIS **Foundantions** Benchmark for OCI with OCI architecture best practices.

**Foundantions** is mispelled

**Comment by andrecorreaneto** [comment]
Fixed.
