### ISSUE TITLE
Adding multiple spoke VCNs to the landing zone "hub and spoke" architecture

### ISSUE THREAD

**Issue by mohabh88** [oracle-quickstart/oci-cis-landingzone-quickstart#49]
Hello Team,

We are facing issues adding multiple spoke VCNs into the hub and spoke landing zone architecture using the default Terraform ".zip" folder. Is there any plan for adding additional spokes in the near future? If already exists, by any chance, please refer us to it to try. This is really an important matter for us to continue working with our defined/plotted architecture. 

Thank you very much in advance for your time and consideration. Looking forward to hearing from you at your earliest convenience. 

Kind regards,
Mohab

**Comment by andrecorreaneto** [comment]
Hi mohabh88, 

please provide more details about the issues you're facing. Landing Zone does support multiple spokes today. All you need to do is providing multiple CIDRs to the vcn_cidrs variable in an array. Each CIDR defines one VCN. Please check https://github.com/oracle-quickstart/oci-cis-landingzone-quickstart/blob/main/VARIABLES.md for vcn_cidrs.

Thanks,

Andre.

**Comment by andrecorreaneto** [comment]
Worked through it with Mohab.
