### ISSUE TITLE
Compliance report pulling old Tenancy name

### ISSUE THREAD

**Issue by LotToLearn** [oracle-quickstart/oci-cis-landingzone-quickstart#50]
Hi, Running the CIS compliance report via Python -- it works fine and outputs the reports as it should.

Only thing is, we have renamed our Tenancy and it is somehow pulling the old tenancy name -- any idea why?

**Comment by Halimer** [comment]
Thank you for bringing this to our attention. The reason you are seeing your old tenancy name is because we are using the tenancy's description not the tenancy's name as part of the file name.  We will fix this in our next release.
