### ISSUE TITLE
Error launching running the Landing zone with a preconfig. 

### ISSUE THREAD

**Issue by nishanbrown** [oracle-quickstart/oci-cis-landingzone-quickstart#53]
Hello we are constantly getting permission issues when running the landing zone as a non admin. 
We ran the pre-config, in the root compartment before running the main config. After the pre-config ran successfully we added ourselves in the provisioning group created from the pre-config. Then we choose the advanced option and changed the group permission to "USE" instead of  "CREATE". Then we specified name of all the groups created by the pre-config in the name of the groups. We still got the following permission error when running the main config. Any help will be really appreciated, thanks in advance! 
![image](https://user-images.githubusercontent.com/47416629/156042138-ea8849d6-34eb-4ec0-beb4-44f4ecb3f93e.png)

**Comment by andrecorreaneto** [comment]
Hi Nishan, as discussed, re running the plan/apply fixes the problem. But we will update the code to for making vaults waiting for compartments to be fully available.
