### ISSUE TITLE
Ability to create subnets with specific names

### ISSUE THREAD

**Issue by mohabh88** [oracle-quickstart/oci-cis-landingzone-quickstart#54]
Hello Team,

We would like to be able to create subnets with specific names from the OCI console rather than modifying the terraform scripts i.e., "net_vcn.tf". We would like to have such a feature, if possible. 

Thank you very much in advance for your time and consideration. Looking forward to hearing from you about the possibility of having this done soon with specifying ETAs, if found.

**Comment by Halimer** [comment]
You can customize the subnet names in Oracle Resource Manager by selecting **Advanced Options** under **Networking - Generic VCNs** then entering the subnet names in the _Subnets Custom Names_ field.
