### ISSUE TITLE
Need to automate creating enclosing compartment

### ISSUE THREAD

**Issue by alihushamme** [oracle-quickstart/oci-cis-landingzone-quickstart#59]
I need to automate enclosing compartment. how to convert the variable "existing_enclosing_compartment_ocid" in quickstart-input.tfvars to a local block input driven from compartment resource creation without touching the other CIS config and modules tf files?

We need to include the enclosing compartment part of terraform automation.

**Comment by andrecorreaneto** [comment]
If you say use_enclosing_compartment=true and don't supply existing_enclosing_compartment_ocid, an enclosing compartment is created under the Root compartment named ${var.service_label}-top-cmp.

If you want a different name for the root compartment, in line 15 of locals.tf change "${var.service_label}-top-cmp" to the desired name.

If you want to create the enclosing compartment somewhere else than the Root compartment, change line 72 of iam_compartments.tf so the parent_id reflects the ocid of the desired parent compartment.

**Comment by alihushamme** [comment]
Hello can you please re-open the GitHub issue?
I followed above steps and if I don't provide existing enclosing compartment ID I am getting below error. I managed to overcome this error by commenting out contents of ../modules/security/vss/main.tf

```
[ibmmas:config]$ terraform plan -var-file="quickstart-input.tfvars"
╷
│ Warning: Provider oci is undefined
│ 
│   on iam_compartments.tf line 69, in module "lz_top_compartment":
│   69:   providers = { oci = oci.home }
│ 
│ Module module.lz_top_compartment does not declare a provider named oci.
│ If you wish to specify a provider configuration for the module, add an entry for oci in the required_providers block within the module.
│ 
│ (and 18 more similar warnings elsewhere)
╵
╷
│ Error: Invalid for_each argument
│ 
│   on ../modules/security/vss/main.tf line 37, in resource "oci_vulnerability_scanning_host_scan_target" "these":
│   37:   for_each = var.scan_targets
│     ├────────────────
│     │ var.scan_targets is a map of object, known only after apply
│ 
│ The "for_each" value depends on resource attributes that cannot be determined until apply, so Terraform cannot predict how many instances will be created. To work around this, use the
│ -target argument to first apply only the resources that the for_each depends on.
╵
[ibmmas:config]$
```

**Comment by alihushamme** [comment]
@andrecorreaneto FYI ^^
