### ISSUE TITLE
provider alias doesn't work with terraform 1.x format with provider source mismatch between oracle/oci and hashicorp/oci

### ISSUE THREAD

**Issue by luckeyca** [oracle-quickstart/oci-cis-landingzone-quickstart#62]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version and Provider Version

terraform: v1.2.2
oracle/oci: 4.78.0

### Affected Resource(s)

ALL. Issue is with the provider source defined as "oracle/oci" mismatching with provider alias always from "hashicorp/oci"

### Terraform Configuration Files

```hcl
provider.tf
terraform {
  required_version = "~> 1.2.2"

  required_providers {
    oci = {
      source                = "oracle/oci"
      version               = "~> 4.78.0"
      configuration_aliases = [oci.home]
    }
  }
}

module.tf example

provider "oci" {
  alias  = "home"
  region = var.region
}

module "lz_top_compartment" {
  count     = var.extend_landing_zone_to_new_region == false && var.use_enclosing_compartment == true && var.existing_enclosing_compartment_ocid == null ? 1 : 0
  source    = "../modules/iam/iam-compartment"
  providers = { oci.home = oci.home }
  compartments = {
    (local.enclosing_compartment.key) = {
      parent_id     = var.tenancy_ocid
      name          = local.enclosing_compartment.name
      description   = "Landing Zone enclosing compartment, enclosing all Landing Zone compartments."
      enable_delete = local.enable_cmp_delete
      defined_tags  = local.compartments_defined_tags
      freeform_tags = local.compartments_freeform_tags
    }
  }
}

full code is here: https://github.com/oracle-quickstart/oci-cis-landingzone-quickstart/config
```

### Expected Behavior

should be able to use terraform 1.x format to set the provider and provider alias

### Actual Behavior

Error: Provider type mismatch
│ 
│   on iam_compartments.tf line 74, in module "lz_top_compartment":
│   74:   providers = { oci.home = oci.home}
│ 
│ The local name "oci.home" in the root module represents provider
│ "oracle/oci", but "oci.home" in module.lz_top_compartment represents
│ "hashicorp/oci".
│ 
│ Each provider has its own distinct configuration schema and provider types,
│ so this module's "oci.home" can be assigned only a configuration for
│ hashicorp/oci, which is not required by module.lz_top_compartment.

### Steps to Reproduce

1. `terraform init`

**Comment by andrecorreaneto** [comment]
luckeyca, you need three things to move to oracle/oci from hashicorp oci:

1. In provider.tf:
terraform {
  required_version = "~> 1.2.2"

  required_providers {
    oci = {
      source                = "oracle/oci"
      version               = "~> 4.78.0"
      configuration_aliases = [oci.home]
    }
  }
}

2. In **ALL** Landing Zone modules:
terraform {
  required_providers {
    oci = {
      source = "oracle/oci"
    }
  }
}

3. And replace the provider in an existing state file if running Terraform CLI:
> terraform state replace-provider hashicorp/oci oracle/oci
