### ISSUE TITLE
Deployment error - local.home_region_key is null

### ISSUE THREAD

**Issue by bkjain40** [oracle-quickstart/oci-cis-landingzone-quickstart#73]
@andrecorreaneto

Facing below error during deployment 

Error: Invalid index
  on provider.tf line 15, in provider "oci" 
  15:   region               = local.regions_map[local.home_region_key]
    ├────────────────
    │ local.home_region_key is null
    │ local.regions_map is object with 34 attributes
Can't use a null value as an indexing key.

**Comment by andrecorreaneto** [comment]
@bkjain40 

please let us know about the following:

- you're input variables
- are you deploying via terraform cli or OCI Resource Manager.

Thanks.

**Comment by andrecorreaneto** [comment]
Okay. I've just deployed as you're trying and it went smooth. 
I believe you were in Ask the Architect webinar, right? Please reach out over email.

**Comment by bkjain40** [comment]
@andrecorreaneto 
Thanks for your time this got resolved
