### ISSUE TITLE
Does deploying Landing Zone considers Identity Domains

### ISSUE THREAD

**Issue by bkjain40** [oracle-quickstart/oci-cis-landingzone-quickstart#74]
My OCI tenancy is with Identity Domain. I selected the compartment that has new domain (instead of default domain), however all the groups and policies are created under the default domain.
Does landing zone considers the domain ? I was expecting the groups and policies to be created under the domain that we had created. 

Thanks in advance. 
![2022-10-04_14-56-05](https://user-images.githubusercontent.com/114725096/193955581-630a126d-52f9-4c68-8307-5dae0c5b7e71.png)
![2022-10-04_14-59-04](https://user-images.githubusercontent.com/114725096/193955629-11bca0f3-5874-490a-bfc2-0e9efe210720.png)

**Comment by andrecorreaneto** [comment]
Hello @bkjain40, currently the Landing Zone manages groups in the default identity domain only.

**Comment by bkjain40** [comment]
Thanks @andrecorreaneto for clarification
