### ISSUE TITLE
Value for undeclared variable

### ISSUE THREAD

**Issue by gillfimj** [oracle-quickstart/oci-cis-landingzone-quickstart#75]
During the terrfaform plan step, received the warning, "The root module does not declare a variable named "subnets_name"". This is due to the mismatch between the variable name in the quickstart-input.tfvars file and the variables.tf file in the config directory. Please correct make them the same so this warning does not appear.

**Comment by andrecorreaneto** [comment]
Thanks @gillfimj. We'll have that fixed in the next release.
