### ISSUE TITLE
Private compute instance in DMZ cannot reach anything thru service gateway

### ISSUE THREAD

**Issue by gillfimj** [oracle-quickstart/oci-cis-landingzone-quickstart#77]
I deployed the Hub/Spoke configuration with DMZ. I would have expected the DMZ indoor route table to include a route rule that goes through the NAT gateway. I found that it was configured with the Internet Gateway. I searched through the code and found that while the NAT gateway was created, it really wasn't being used anywhere. Since the indoor subnet is a private subnet, it needs to have the NAT gateway route in order to find it's way to the allowed outside network resources, like services for OS updates. Was this by design? If so, then how would one do OS updates on private devices? If not, then this might be a bug that should be addressed.

**Comment by Halimer** [comment]
The DMZ VCN when not being used for a next generation firewall it is tested for two deployment types:
- A bastion server that can use the bastion NSG to access servers in the spoke VCNs from either internet or on-premises.
- A Public Network Load Balancer in front of a private Load Balancer to consolidate access from the internet or a single Network Load Balancer or Load Balancer 
The reason the NAT gateway is created is due to how the network module(https://github.com/oracle-quickstart/oci-cis-landingzone-quickstart/tree/main/modules/network/vcn-basic) functions.

**Comment by gillfimj** [comment]
So how would anything be able to do any kind of OS updates then since there's no way to get out? That doesn't seem like practical testing.

**Comment by gillfimj** [comment]
From a general fundamental standpoint, doesn't a private subnet need to have a NAT gateway for the default route and not the internet gateway? That's really my point.

**Comment by gillfimj** [comment]
I'm also curious how any of the other VCNs created besides the DMZ are supposed to access the public internet, for things like interactions with other vendors such as Kubernetes, Docker, etc. Does it mean that anything that needs access to any public endpoint needs to reside in the DMZ?

**Comment by Halimer** [comment]
> From a general fundamental standpoint, doesn't a private subnet need to have a NAT gateway for the default route and not the internet gateway? That's really my point.

There are two types of subnet in [OCI Networking](https://docs.oracle.com/en-us/iaas/Content/Network/Concepts/overview.htm): Private means VNICs in the subnet can't have public IPv4 addresses and internet communication with IPv6 endpoints will be prohibited. Public means VNICs in the subnet can have public IPv4 addresses and internet communication is permitted with IPv6 endpoints.

The variable no_internet_access determines if subnets will be provisioned with IGWs and NAT Gateways as defined in: [https://github.com/oracle-quickstart/oci-cis-landingzone-quickstart/blob/main/VARIABLES.md#networking---public-connectivity-variables](https://github.com/oracle-quickstart/oci-cis-landingzone-quickstart/blob/main/VARIABLES.md#networking---public-connectivity-variables)

**Comment by Halimer** [comment]
> I'm also curious how any of the other VCNs created besides the DMZ are supposed to access the public internet, for things like interactions with other vendors such as Kubernetes, Docker, etc. Does it mean that anything that needs access to any public endpoint needs to reside in the DMZ?

The DMZ VCN is primarily for NextGen Firewall deployments. You may want to consider deploying a hub & spoke architecture without a DMZ VCN.  In this configuration all VCNs will have an IGW in public subnet and NATGWs in private subnets plus SGWs for accessing OCI services.  Also all the VCNs will be able to communicate with each other.  You can see the [Network/Hub variables](https://github.com/oracle-quickstart/oci-cis-landingzone-quickstart/blob/main/VARIABLES.md#networking---hubspoke-variables) for more information.
