### ISSUE TITLE
Reverse engineering a landing zone with OKIT

### ISSUE THREAD

**Issue by rheadrickTSC** [oracle-quickstart/oci-cis-landingzone-quickstart#80]
I understand there is an issue reverse engineering these landing zones with OKIT and that there is cooperation between OKIT and landing zone development.  My question is, are the two expected to work together at some point so that OKIT can be used to roll out a landing zone?

**Comment by Halimer** [comment]
We are in communication with the OKIT team and are looking at ways to algin.

**Comment by rheadrickTSC** [comment]
I have another question:  I will be subscribing to the OCI Observation & Management tool.  In which compartment would you recommend it place it in landing zone such as hub and spoke or the other?

**Comment by Halimer** [comment]
In the landing zone infrastructure logging is consolidated to the Security Compartment.  Depending on how you are using OCI Observation and Management application, database, or infrastructure the service should be created in the corresponding compartment.  If you are deploying any infrastructure requiring a VCN either hub VCN or a shared services VCN would be a good spot for that.
