### ISSUE TITLE
Issue generating CSV for File Storage Service when obp is enabled (no other params)

### ISSUE THREAD

**Issue by tpresence** [oracle-quickstart/oci-cis-landingzone-quickstart#82]
From cis_reports.py clone on Dec 09, 2022.
Data collection appears to work, but when the script is generating the CSV files, one of the elements doesn't appear to have upper().

CSV: Storage - File Storage Service_4.3.1 --> engitdev/cis_Storage_File_Storage_Service_4-3-1.csv
Traceback (most recent call last):
  File "./cis_reports.py", line 4137, in <module>
    execute_report()
  File "./cis_reports.py", line 4102, in execute_report
    csv_report_directory = report.generate_reports(int(cmd.level))
  File "./cis_reports.py", line 3918, in generate_reports
    self.__obp_analyze_tenancy_data()
  File "./cis_reports.py", line 3126, in __obp_analyze_tenancy_data
    elif source['log_group_id'].upper() == "_Audit_Include_Subcompartment".upper():
AttributeError: 'NoneType' object has no attribute 'upper'

**Comment by Halimer** [comment]
This should be resolved in release 2.5.1 we just released
