### ISSUE TITLE
Roadmap for the middle ground deployment lifecycle approach

### ISSUE THREAD

**Issue by tre7roja** [oracle-quickstart/oci-cis-landingzone-quickstart#85]
Hi,

Based on the documentation below, I want to know if you have plan to release this feature in the next month.
Else perhaps you have any suggestion to implement this middle ground approach (an example).

> The middle ground approach is typically used by organizations that see network and security as shared services and want to provide separate environments for application and database resources. This is coming soon in the Landing Zone.

Thanks in advance

BR

**Comment by andrecorreaneto** [comment]
Hi tre7roja,
the middle ground approach in all its different nuances will be feasible through letting users build their own CIS compliant Landing Zones in a declarative fashion. Please see the recently released [standalone compartments module](https://github.com/oracle-quickstart/terraform-oci-cis-landing-zone-iam-compartments), the first one of a series. Policies and networking are in the pipeline and will be released in the next few weeks.
Thanks.
