### ISSUE TITLE
Required policies for Autonomous Database using Private Endpoint missing

### ISSUE THREAD

**Issue by Manjinder-Singh-SG** [oracle-quickstart/oci-cis-landingzone-quickstart#89]
The required policies to allow DB Admin Group to be able to provision ADB with Private Endpoint are missing. Policies can be found at https://docs.oracle.com/en-us/iaas/autonomous-database-shared/doc/iam-private-endpoint-configure-policies.html

**Comment by andrecorreaneto** [comment]
Thanks. We'll check and provide the fix.

**Comment by Halimer** [comment]
Fixed in release 2.5.5
