### ISSUE TITLE
spoke vcn limit for hub_spoke_architecture

### ISSUE THREAD

**Issue by mhca99** [oracle-quickstart/oci-cis-landingzone-quickstart#93]
Hi, 

In the current oci landing zone Terraform code, there is spoke vcn limit mentioned that we can have maximum nine spoke vcn connected to hub for hub_spoke_architecture.  While this conditionally be changed in variable section , is this hard limitation in OCI cloud ? Will changing this value e.g. to 30 cause any implications  or this was placed to avoid slow Terraform refresh etc.?

As per oracle doc "https://docs.oracle.com/en/solutions/hub-spoke-network-drg/index.html#GUID-FB5990CB-A23B-482D-80F4-AE4A548DEC9C"  maximum 300 vnc can be connected via DRG.

Whats the maximum recommended spoke vcn we can have ? and whats the hard limit ?

Thanks

**Comment by andrecorreaneto** [comment]
Hello mhca99,
I think that limit in the TF code is a reminiscent when we had LPG connecting the VCNs. You can safely disable that, as we now use the DRG to connect. And you're spot on the soft limit, 300. Not aware of the hard limit. If you need to go beyond 300, please open an SR justifying. I don't think there's a recommendation on the maximum number, it all depends on what you're trying to achieve. Hope this helps.

**Comment by mhca99** [comment]
Thanks Andre for the clarification.
