### ISSUE TITLE
cis_reports.py - SyntaxError on a number of lines

### ISSUE THREAD

**Issue by dns-prefetch** [oracle-quickstart/oci-cis-landingzone-quickstart#95]
Hi

There are a number of special characters embedded in the python script that cause the following errors.  This is not the full list, but an example.  e.g the \xa9 repeats in a number of places.

Also the Copywrite symbol at end of script fails and generates error.

My runtime environment is Linux OL8 on Intel.

Cheers, Michael

SyntaxError: Non-UTF-8 code starting with '\x93' in file cis_reports.py on line 177, but no encoding declared; see https://python.org/dev/peps/pep-0263/ for details

SyntaxError: Non-UTF-8 code starting with '\x93' in file cis_reports.py on line 177, but no encoding declared; see https://python.org/dev/peps/pep-0263/ for details

SyntaxError: Non-UTF-8 code starting with '\x93' in file cis_reports.py on line 177, but no encoding declared; see https://python.org/dev/peps/pep-0263/ for details

SyntaxError: Non-UTF-8 code starting with '\x96' in file cis_reports.py on line 333, but no encoding declared; see https://python.org/dev/peps/pep-0263/ for details

SyntaxError: Non-UTF-8 code starting with '\x96' in file cis_reports.py on line 333, but no encoding declared; see https://python.org/dev/peps/pep-0263/ for details

SyntaxError: Non-UTF-8 code starting with '\xa9' in file cis_reports.py on line 4176, but no encoding declared;

**Comment by andrecorreaneto** [comment]
Hi Michael, we tried but could not reproduce it in Intel OL8. Are there any other details?
Cheers.

**Comment by dns-prefetch** [comment]
Hi Andre

thanks for getting back to me.

I repeated my testing this morning, but I'm not getting the same issues.  I think the problem must have been environmental in on my virtualbox VM.  The characters still exist in the python code (I checked), but python doesn't complain today.

My apologies for waisting your time.

On a separate note.  When I want to run the cis_reports.py from my virtualbox VM, I make a couple of code changes to handle security token (-st instead of -dt etc).  Is this something you could support in the near future?  I can add my code to another ticket if any use?

Have a good day.

Cheers, Michael.

**Comment by Halimer** [comment]
Hi Michael, 

We would be happy to add the security token feature to the cis_reports.py script.  If you want to provide the code via snippet to this issue we can get it in an upcoming release.

Thank you.

**Comment by Halimer** [comment]
@dns-prefetch Thank you so much for your contribution.  We added it in PR https://github.com/oracle-quickstart/oci-cis-landingzone-quickstart/pull/108.  We attributed you in the code.
