### ISSUE TITLE
Routing question when extending to new region

### ISSUE THREAD

**Issue by gillfimj** [oracle-quickstart/oci-cis-landingzone-quickstart#96]
When extending the landing zone to a new region, is it expected that the VCNs from the home region are NOT included in the route tables in the extended region? If that is the expected behavior and we need to be able to communicate to instances between regions, what's the best way to make that happen? Ideally, the VCN cidrs from the home region would have to be added to the route tables in the extended region, correct? Not entirely sure how to make that happen. The new region was extended via Terraform workspaces following this link:

[https://www.ateam-oracle.com/post/creating-a-secure-multi-region-landing-zone](https://www.ateam-oracle.com/post/creating-a-secure-multi-region-landing-zonel)

**Comment by gillfimj** [comment]
I had a thought on how to resolve this and would like confirmation if this is the way to approach the problem. Given that the extended region is created via a terraform workspace and a separate config file, does it make sense to add the VCNs from the home region to the list of onprem_cidrs and onprem_src_ssh_cidrs to provide the necessary security settings to allow the access between regions? Obviously, a similar task would need to be done in the home region with the extended region's VCNs. Are there caveats to doing it this way or a better way to approach this?

**Comment by andrecorreaneto** [comment]
Hi gillfimj,
You're right. When extending, set onprem_cidrs and onprem_src_ssh_cidrs. They will be used to build route rules and NSGs in the new region.
Thanks.

**Comment by gillfimj** [comment]
Terrific. Thanks so much!
