### ISSUE TITLE
Multiple LZ Repos - Which to choose?

### ISSUE THREAD

**Issue by agtpgh** [oracle-quickstart/oci-cis-landingzone-quickstart#99]
Hi,

We are looking to test the OCI landing zone package and noted there appear to be multiple 'landing zone' repos on the Oracle GitHub.

[oci-landing-zones](https://github.com/oracle-quickstart/oci-landing-zones)
[oci-cis-landingzone-quickstart](https://github.com/oracle-quickstart/oci-cis-landingzone-quickstart)
[oci-enterprise-scale-baseline-landing-zone](https://github.com/oracle-quickstart/oci-enterprise-scale-baseline-landing-zone)

Could you advise what the difference between these 3 is and which is considered the actively developed LZ? Our goal is to utilise the latest (v2 we believe) version that is CIS benchmarked. We are an enterprise business looking to use the hub and spoke networking with options to define multiple VCNs per-application, unsure whether this will have an impact on LZ choice?

**Comment by flynnkc** [comment]
Hello @agtpgh,

The OCI CIS Landing Zone QuickStart is a aligned to CIS OCI Benchmark to meet the needs of our customers for a reference architecture for tenancy design that follows security best practices with an operational component in the form of automation and validation tooling.

The OCI CIS Landing Zone is being actively maintained. In addition, Hub & Spoke network architectures are supported by this Landing Zone. Multiple VCNs can be defined within a single Landing Zone deployment as well.

I can't comment on other landing zones in OCI as I don't have visibility into their development teams. If you're trying to align with the CIS benchmark, the OCI CIS Landing Zone is a great option as CIS compliance is one of the projects core tenets.

- KC

**Comment by agtpgh** [comment]
Hi KC,

Thank you for the response and explanation. When we were at Oracle Cloud World they had a stand for the Landing Zone (https://github.com/oracle-quickstart/oci-landing-zones) and we mentioned there that the Oracle GitHub has multiple relases.

It seems there are various teams trying to achieve the same thing or perhaps variants on a similar theme. It would be great if each of the Oracle repos could combine to bring the best of each to a single Landing Zone with templates that allow customers to pick the right fit. Otherwise it feels like a lot of duplication going on, though this is purely our view as outsiders trying to understand which to use :)

In the end the business is aligning with the repo linked above as they were at Cloud World and confirmed they support CIS and will support various ISO/PCI compliance with coming releases.
